### ISSUE TITLE
Add larivaar

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/gurmukhi-utils#136]
https://github.com/ShabadOS/theme-tool/pull/1#discussion_r418789452
I think this will also be useful for mobile.

**Comment by Sarabveer** [comment]
@Harjot1Singh do we want to include larivaar in gurmukhi-utils or just do in in app.

**Comment by Harjot1Singh** [comment]
> @Harjot1Singh do we want to include larivaar in gurmukhi-utils or just do in in app. 

I think it may be worth moving this into GU. Do you think others, or yourself would find it useful?

**Comment by Sarabveer** [comment]
Sure, it could be moved into GU. I personally replace spaces with Zero-Witdh Spaces (U+200B) for Larivaar.

How would GU implement assist though, isn't that up to the app?

**Comment by saihaj** [comment]
Yeah assist will depend on the app

**Comment by bhajneet** [comment]
Closing without resolution. This issue either affects too few users or there are too many issues with higher impact to be working on. It is possible to re-open or re-visit this issue at a later time. If you feel this issue is important, please give a thumbs-up reaction to the first post. You may track this issue from the pinned meta-tracker at the top of the issues home page.

**Comment by Sarabveer** [comment]
I thought about this more, and I realized this would be useful. Currently I have a set of regex lookups that properly format for larivaar.

I will look into implementing this sooner or later.

**Comment by bhajneet** [comment]
Can you give an example of how it's helpful? We just remove spaces at this time, so wondering what else is happening with regex

**Comment by bhajneet** [comment]
I still have no idea if there is a benefit to this function (which as far as I know simply strips whitespace), so closing for now, but open to implementing it if given some logic/programming requirements
