### ISSUE TITLE
Difference in Transliteration for D and d

### ISSUE THREAD

**Issue by amansx** [shabados/gurmukhi-utils#203]
### Describe the bug

ਆਦਿ ਸਚੁ ਜੁਗਾਦਿ ਸਚੁ ॥
on SikhiToTheMax transliterates to::
aadh sach jugaadh sach ||

whereas utilities translate to::
aad sach jugaad sach |

notice the missing "dh"
is the algorithm complete?

**Comment by bhajneet** [comment]
When opening a new issue, if you have a question like this, then please avoid opening a bug report. There is a question template available when opening new issues!

In short: Yes, the algorithm is complete. This is by design. It will be changing again to closer match the ISO standard which is based on transliteration techniques dating over a century before STTM was released.

Feel free to hop on our Slack and chat with us for more info!

https://chat.shabados.com
